# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='shortener',
        ),
        migrations.AddField(
            model_name='link',
            name='shortner',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
